apiVersion: apps/v1
kind: Deployment
metadata:
  name: notes-api-deployment
  labels:
    app: notes-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notes-api
  template:
    metadata:
      labels:
        app: notes-api
    spec:
      containers:
      - name: notes-api
        image: manekshms/notes-api
        ports:
        - containerPort: 3000