apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
  labels:
    app: client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata: 
      name: client-deployment
      labels:
        app: client
    spec:
      containers:
        - name: client-deployment
          image: manekshms/notes-client
          ports:
            - containerPort: 80
    
